package main

import (
	"flag"
	"fmt"
	"strings"
)

// completion prints a completion script for the named shell.
//
// The script is generated here, from the same verb table main dispatches on,
// rather than committed to the tree. A committed completion file is a second
// copy of the verb list, and nothing fails when the two drift: the verb still
// works, it just stops being completable, which nobody files a bug about.
// Generating it means a verb added to the dispatch appears in the next
// generated script with no further step, and completion_test.go fails the
// build if it does not.
//
// This is also the honest way to live with the no-shell-scripts rule
// (CONTRIBUTING.md, enforced by internal/hygiene): a completion is shell by
// definition, so it is emitted from Go at the user's request instead of
// rotting in a .sh file the hygiene check would rightly reject.
func completion(args []string) error {
	fs := flag.NewFlagSet("completion", flag.ContinueOnError)
	if err := parseFlags(fs, args); err != nil {
		return err
	}
	script, err := completionScript(fs.Arg(0))
	if err != nil {
		return err
	}
	fmt.Print(script)
	return nil
}

// completionScript renders the script for one shell, or says which shells
// exist. Split from completion so a test can read the output without
// capturing stdout.
func completionScript(shell string) (string, error) {
	switch shell {
	case "bash":
		return bashCompletion(), nil
	case "zsh":
		return zshCompletion(), nil
	case "fish":
		return fishCompletion(), nil
	}
	// Name the shells that work rather than only rejecting the one that does
	// not: the reader's next move is retyping the command, and making them
	// guess the spelling turns one failed attempt into three.
	if shell == "" {
		return "", fmt.Errorf("`dibs completion` needs a shell: bash, zsh or fish")
	}
	return "", fmt.Errorf("no completion for %q: the shells are bash, zsh and fish", shell)
}

// verbDocs pairs every dispatched verb with the first line of its usage entry,
// in the order the usage text lists them.
//
// The descriptions are parsed out of the usage constant with the same rule
// styledUsage applies when it colours the help: the invocation runs to the
// first double space, the explanation follows. Reusing the convention rather
// than keeping a second table means a reworded help line rewords the
// completion too, and TestEverySubcommandIsInTheUsageText already guarantees every verb
// in `commands` has a usage line to be found on.
func verbDocs() ([]string, map[string]string) {
	docs := make(map[string]string, len(commands))
	var order []string
	for _, line := range strings.Split(usage, "\n") {
		if !strings.HasPrefix(line, "  dibs ") {
			continue
		}
		rest := line[len("  dibs "):]
		invocation, doc := rest, ""
		if i := strings.Index(rest, "  "); i >= 0 {
			invocation, doc = rest[:i], strings.TrimSpace(rest[i:])
			// A first line that runs on into the next leaves a dangling comma,
			// which reads like a rendering fault in a completion menu.
			doc = strings.TrimSuffix(doc, ",")
		}
		verb, _, _ := strings.Cut(invocation, " ")
		if _, seen := docs[verb]; seen {
			continue // first line wins: later mentions are flag variants
		}
		docs[verb] = doc
		order = append(order, verb)
	}
	return order, docs
}

func bashCompletion() string {
	verbs, _ := verbDocs()
	var b strings.Builder
	b.WriteString("# bash completion for dibs. Generated by `dibs completion bash`;\n")
	b.WriteString("# regenerate rather than edit, so the verb list cannot drift from the CLI.\n")
	b.WriteString("_dibs() {\n")
	b.WriteString("\tlocal cur=${COMP_WORDS[COMP_CWORD]}\n")
	b.WriteString("\tCOMPREPLY=()\n")
	b.WriteString("\tif [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	b.WriteString("\t\tCOMPREPLY=($(compgen -W \"" + strings.Join(verbs, " ") + "\" -- \"$cur\"))\n")
	b.WriteString("\tfi\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _dibs dibs\n")
	return b.String()
}

func zshCompletion() string {
	verbs, docs := verbDocs()
	var b strings.Builder
	b.WriteString("#compdef agents\n")
	b.WriteString("# zsh completion for dibs. Generated by `dibs completion zsh`;\n")
	b.WriteString("# regenerate rather than edit, so the verb list cannot drift from the CLI.\n")
	b.WriteString("_dibs() {\n")
	b.WriteString("\tlocal -a verbs\n")
	b.WriteString("\tverbs=(\n")
	for _, v := range verbs {
		entry := v
		if doc := docs[v]; doc != "" {
			// In a _describe spec the first colon splits verb from description,
			// so a description's own colons have to arrive escaped or everything
			// after them is silently dropped.
			entry += ":" + strings.ReplaceAll(doc, ":", `\:`)
		}
		b.WriteString("\t\t'" + strings.ReplaceAll(entry, "'", `'\''`) + "'\n")
	}
	b.WriteString("\t)\n")
	b.WriteString("\tif (( CURRENT == 2 )); then\n")
	b.WriteString("\t\t_describe -t commands 'agents command' verbs\n")
	b.WriteString("\tfi\n")
	b.WriteString("}\n")
	b.WriteString("_dibs \"$@\"\n")
	return b.String()
}

func fishCompletion() string {
	verbs, docs := verbDocs()
	var b strings.Builder
	b.WriteString("# fish completion for dibs. Generated by `dibs completion fish`;\n")
	b.WriteString("# regenerate rather than edit, so the verb list cannot drift from the CLI.\n")
	b.WriteString("complete -c agents -f\n")
	for _, v := range verbs {
		line := "complete -c agents -n __fish_use_subcommand -a " + v
		if doc := docs[v]; doc != "" {
			doc = strings.ReplaceAll(doc, `\`, `\\`)
			doc = strings.ReplaceAll(doc, "'", `\'`)
			line += " -d '" + doc + "'"
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}
