// Command smoke runs the built binaries and reads what they say about
// themselves.
//
// It exists because 0.0.3 shipped a product that called itself `agents`. The
// rename was thorough in the tree and the whole gate was green, because the
// rename had also rewritten the fixtures the gate compares against:
// doctor_test.go asserted `[mcp_servers.agents]`, so the test agreed with the
// bug. A suite cannot catch a rename error when the rename edits both sides.
//
// So nothing here reads the source, and nothing here is generated from it. The
// expected strings are written out by hand, once, and a rename that misses a
// string has to come and change them deliberately. That is the whole design:
// this file does not move when the code moves.
//
// The checks run against a scratch HOME, not the developer's. Identity surfaces
// print paths, and a machine that already has a data directory would report
// whatever is on disk rather than what a new install gets: which is precisely
// the reading that let ~/.agents survive a release.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// check is one thing the binaries must say, in their own output.
type check struct {
	what string
	bin  string
	args []string
	env  []string
	// want must all appear; reject must not appear at all.
	want   []string
	reject []string
}

// staleNames are the names this product has had, and the one the vocabulary
// rename left behind. None of them may appear in anything a user reads.
// The bare word "agents" is not among them: this output legitimately talks
// about agent sessions. What must not appear is the name in CONFIG-KEY
// position, which is where 0.0.3 published the server and where this check,
// on its first draft, still let it through.
var staleServerNames = []string{
	"mcp_servers.agents", "mcp_servers.lanes",
	`"agents": {`, `"lanes": {`,
	"lanesd", "agentsd", ".agents", ".lanes",
}

func main() { os.Exit(run()) }

// run returns the exit code rather than calling os.Exit, so the scratch homes
// are actually removed: a deferred cleanup does not survive os.Exit.
func run() int {
	// A fresh install with a data directory already in place, so the commands
	// that need one get past their first check and print the thing under test.
	home, err := newHome(strings.Repeat("a1b2c3d4", 8))
	if err != nil {
		fmt.Fprintln(os.Stderr, "smoke: could not build a scratch home:", err)
		return 1
	}
	defer func() { _ = os.RemoveAll(home) }()

	// And one with a secret too short to elide. mcp-config sliced it unguarded
	// and panicked, and because the crash came AFTER the first config block,
	// a check that only looked for the product name passed on the wreckage.
	short, err := newHome("short")
	if err != nil {
		fmt.Fprintln(os.Stderr, "smoke: could not build a scratch home:", err)
		return 1
	}
	defer func() { _ = os.RemoveAll(short) }()

	admin := []string{"HOME=" + home, "DIBS_ADMIN=1", "DIBS_DIR="}

	checks := []check{
		{
			what: "version names the product",
			bin:  "bin/dibs", args: []string{"version"},
			want: []string{"dibs "}, reject: []string{"agents ", "lanes "},
		},
		{
			what: "an unknown verb suggests the right binary",
			bin:  "bin/dibs", args: []string{"borad"},
			want:   []string{"dibs:", "did you mean: dibs board"},
			reject: []string{"agents:", "lanes:", "did you mean: agents", "did you mean: lanes"},
		},
		{
			what: "the admin refusal names the right command",
			bin:  "bin/dibs", args: []string{"mcp-config"},
			want: []string{`"dibs mcp-config"`}, reject: []string{"agents mcp-config", "lanes mcp-config"},
		},
		{
			what: "help is titled for the product",
			bin:  "bin/dibs", args: []string{"--help"},
			want: []string{"dibs:"}, reject: []string{"agents:", "lanes:"},
		},
		{
			// Rejecting a bare "agents" here was wrong and this check caught its
			// own author: a completion DESCRIBES the board as "agents, slots,
			// claims", which is correct English about what the board shows. What
			// must not appear is the program's name in command position.
			what: "completions declare the right command",
			bin:  "bin/dibs", args: []string{"completion", "zsh"},
			want: []string{"#compdef dibs"},
			reject: []string{
				"#compdef agents", "#compdef lanes", "_agents", "_lanes",
				"complete -c agents", "complete -c lanes",
			},
		},
		{
			// The 0.0.3 bug itself: the MCP server was published under the name
			// `agents`, so every harness config generated by that release told
			// its agent to connect to a server that no document mentioned.
			// Both blocks by name. Wanting a bare "dibs" was enough to pass on
			// output that crashed before reaching the second one.
			what: "mcp-config publishes the server under the product name",
			bin:  "bin/dibs", args: []string{"mcp-config"}, env: admin,
			want:   []string{`"dibs": {`, "[mcp_servers.dibs]"},
			reject: staleServerNames,
		},
		{
			what: "mcp-config survives a secret too short to elide",
			bin:  "bin/dibs", args: []string{"mcp-config"},
			env:  []string{"HOME=" + short, "DIBS_ADMIN=1", "DIBS_DIR="},
			want: []string{"[mcp_servers.dibs]"}, reject: []string{"panic:", "goroutine "},
		},
		{
			// A fresh install must be told about ~/.dibs. This runs against a
			// scratch HOME that has one, so a fallback to an inherited directory
			// cannot mask a default that is still wrong.
			what: "doctor reports the current data directory",
			bin:  "bin/dibs", args: []string{"doctor"}, env: admin,
			want: []string{".dibs"}, reject: []string{".agents", ".lanes"},
		},
		{
			what: "the daemon refuses an unknown flag under its own name",
			bin:  "bin/dibd", args: []string{"--nonsense"},
			want: []string{"dibd"}, reject: []string{"lanesd", "agentsd"},
		},
	}

	failed := runChecks(checks)

	docs := checkDocs()
	for _, p := range docs {
		failed++
		fmt.Printf("  FAIL docs: %s\n", p)
	}
	if len(docs) == 0 {
		fmt.Println("  ok   every documented command is one the binary accepts")
	}

	plugins := checkPlugins()
	for _, p := range plugins {
		failed++
		fmt.Printf("  FAIL plugins: %s\n", p)
	}
	if len(plugins) == 0 {
		fmt.Println("  ok   every plugin payload spawns a binary we ship")
	}

	if failed > 0 {
		fmt.Fprintf(os.Stderr, "\n%d smoke check(s) failed: the built binaries do not behave "+
			"the way the docs and install instructions say they do.\nThis runs on the "+
			"artifact, so a fixture that agrees with the bug cannot hide it here.\n", failed)
		return 1
	}
	fmt.Printf("%d smoke checks passed\n", len(checks)+2)
	return 0
}

// runChecks runs each check and prints its verdict, returning how many failed.
func runChecks(checks []check) int {
	failed := 0
	for _, c := range checks {
		// Output, not exit status: several of these are refusals and are
		// SUPPOSED to fail. What matters is the words they use.
		cmd := exec.Command(c.bin, c.args...) // #nosec G204 -- fixed argv
		if c.env != nil {
			cmd.Env = append(os.Environ(), c.env...)
		}
		out, _ := cmd.CombinedOutput()
		problems := judgeOutput(string(out), c)
		if len(problems) == 0 {
			fmt.Printf("  ok   %s\n", c.what)
			continue
		}
		failed++
		fmt.Printf("  FAIL %s: %s\n       %s %v said:\n%s\n",
			c.what, strings.Join(problems, "; "), c.bin, c.args, indent(string(out)))
	}
	return failed
}

// judgeOutput reports what one check's output got wrong.
func judgeOutput(text string, c check) []string {
	var problems []string
	for _, w := range c.want {
		if !strings.Contains(text, w) {
			problems = append(problems, fmt.Sprintf("missing %q", w))
		}
	}
	for _, r := range c.reject {
		if strings.Contains(text, r) {
			problems = append(problems, fmt.Sprintf("still says %q", r))
		}
	}
	return problems
}

// newHome builds a scratch home with just enough of a data directory that the
// commands under test get past their preconditions.
func newHome(secret string) (string, error) {
	home, err := os.MkdirTemp("", "dibs-smoke-")
	if err != nil {
		return "", err
	}
	dir := filepath.Join(home, ".dibs")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	// Nothing here authenticates: the LENGTH is what these commands react to.
	if err := os.WriteFile(filepath.Join(dir, "local.secret"), []byte(secret+"\n"), 0o600); err != nil {
		return "", err
	}
	return home, nil
}

func indent(s string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		b.WriteString("       | " + line + "\n")
	}
	return b.String()
}
