package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"
)

// man renders this CLI's manual page, in mdoc(7), from the usage text.
//
// Generated rather than committed, for the same reason as everything else this
// project derives from a single source: a hand-written man page is a second
// copy of the help text, and nothing fails when the two drift, so the copy
// loses. The release pipeline runs this to put lanes.1 in the archives and the
// Homebrew cask; man_test.go fails the build if a dispatched verb has no entry
// on the page.
//
// The page is assembled from the same `usage` constant `lanes help` prints,
// parsed with the same rule styledUsage applies when it colours the help: the
// invocation runs to the first double space, the explanation follows. So a
// reworded help line rewords the page, and a verb added to the help appears
// here with no further step.
func man(args []string) error {
	fs := flag.NewFlagSet("man", flag.ContinueOnError)
	out := fs.String("out", "", "write the page to this file instead of stdout")
	date := fs.String("date", "", "page date, RFC3339 or YYYY-MM-DD (default today). "+
		"The release passes the commit date so two builds of one commit produce one page")
	if err := parseFlags(fs, args); err != nil {
		return err
	}
	page, err := manPage(*date)
	if err != nil {
		return err
	}
	if *out == "" {
		fmt.Print(page)
		return nil
	}
	// 0644: documentation, and the release archive re-applies its own modes.
	return os.WriteFile(*out, []byte(page), 0o644) // #nosec G306 -- a public man page
}

// manVerb is one entry of the usage text: an invocation and its explanation.
type manVerb struct {
	invocation string // "probe --pid N"
	text       string // the explanation, continuation lines joined
}

// manSection is one heading's worth of verbs, in the order the help lists
// them: the grouping is documentation too, because it says who each verb is
// for.
type manSection struct {
	title string
	verbs []manVerb
}

// parseUsage splits the usage constant into its one-line summary, its verb
// sections and its environment line.
//
// The shapes it relies on are the ones styledUsage already relies on: a verb
// line starts with two spaces and "lanes ", its continuations are indented
// further, a heading ends with a colon (possibly after wrapping), and the
// environment block opens with "env:". A new line shape in the usage text
// breaks the styling too, so the two cannot rot apart silently.
func parseUsage() (summary string, sections []manSection, env string) {
	lines := strings.Split(usage, "\n")
	_, summary, _ = strings.Cut(lines[0], ": ")
	heading := ""
	inEnv := false
	for _, line := range lines[1:] {
		switch {
		case inEnv:
			env += " " + strings.TrimSpace(line)
		case strings.HasPrefix(line, "env: "):
			inEnv = true
			env = strings.TrimPrefix(line, "env: ")
		case strings.HasPrefix(line, "  lanes "):
			rest := line[len("  lanes "):]
			invocation, text := rest, ""
			if i := strings.Index(rest, "  "); i >= 0 {
				invocation, text = rest[:i], strings.TrimSpace(rest[i:])
			}
			s := &sections[len(sections)-1]
			s.verbs = append(s.verbs, manVerb{invocation: invocation, text: text})
		case strings.HasPrefix(line, "     "):
			s := &sections[len(sections)-1]
			v := &s.verbs[len(s.verbs)-1]
			v.text += " " + strings.TrimSpace(line)
		case strings.TrimSpace(line) == "":
			// blank: nothing to close, the shapes above are self-delimiting
		default:
			// A heading, which may wrap: accumulate until the colon arrives.
			heading += strings.TrimSpace(line) + " "
			if strings.HasSuffix(strings.TrimSpace(heading), ":") {
				title := strings.TrimSuffix(strings.TrimSpace(heading), ":")
				sections = append(sections, manSection{title: title})
				heading = ""
			}
		}
	}
	return summary, sections, strings.TrimSpace(env)
}

// manPage renders the whole page. Split from man so a test can read it
// without capturing stdout.
func manPage(date string) (string, error) {
	when, err := manDate(date)
	if err != nil {
		return "", err
	}
	summary, sections, env := parseUsage()

	var b strings.Builder
	b.WriteString(".\\\" lanes.1: generated by `lanes man` from the CLI's own usage text.\n")
	b.WriteString(".\\\" Regenerate rather than edit: a hand-maintained page is a second copy\n")
	b.WriteString(".\\\" of the help, and the copy loses.\n")
	b.WriteString(".Dd " + when.Format("January 2, 2006") + "\n")
	b.WriteString(".Dt LANES 1\n")
	b.WriteString(".Os\n")
	b.WriteString(".Sh NAME\n.Nm lanes\n.Nd " + roffText(summary) + "\n")
	b.WriteString(".Sh SYNOPSIS\n.Nm\n.Ar verb\n.Op Ar argument ...\n")
	b.WriteString(".Sh DESCRIPTION\n")
	b.WriteString(".Nm\nis the human window into the coordination board the\n")
	b.WriteString("lanesd daemon serves: inspect state, follow the live event stream,\n")
	b.WriteString("verify ledger integrity.\n")
	b.WriteString("The verbs are grouped as the help text groups them, because the grouping\n")
	b.WriteString("says who each verb is for.\n")
	for _, s := range sections {
		b.WriteString(".Ss " + roffText(s.title) + "\n")
		b.WriteString(".Bl -tag -width Ds\n")
		for _, v := range s.verbs {
			b.WriteString(manItem(v.invocation))
			writeSentences(&b, v.text)
		}
		b.WriteString(".El\n")
	}
	b.WriteString(".Sh ENVIRONMENT\n")
	writeEnvironment(&b, env)
	b.WriteString(".Sh EXIT STATUS\n.Ex -std\n")
	b.WriteString("An unknown verb or flag exits 2, so a typo in a script cannot read as\nsuccess.\n")
	return b.String(), nil
}

// manDate resolves the page date. The release passes the commit date so two
// builds of one commit produce one page: the same rule the archive applies to
// its file timestamps, applied to the one file whose content carries a date.
func manDate(date string) (time.Time, error) {
	if date == "" {
		return time.Now(), nil
	}
	for _, layout := range []string{time.RFC3339, "2006-01-02"} {
		if t, err := time.Parse(layout, date); err == nil {
			return t, nil
		}
	}
	return time.Time{}, fmt.Errorf("--date %q is neither RFC3339 nor YYYY-MM-DD", date)
}

// manItem renders one verb's tag line. The verb itself is a .Cm; whatever
// follows it in the invocation is carried literally, with hyphens escaped so
// options keep real minus signs rather than typographic hyphens.
func manItem(invocation string) string {
	fields := strings.Fields(invocation)
	line := ".It Cm " + fields[0]
	for _, f := range fields[1:] {
		line += " " + strings.ReplaceAll(roffText(f), "-", `\-`)
	}
	return line + "\n"
}

// sentenceEnd finds a sentence boundary without being fooled by an ellipsis:
// the character before the stop must not itself be a stop, or "notify,..."
// splits in the middle of its own dots.
var sentenceEnd = regexp.MustCompile(`([^.?!])([.?!]) `)

// writeSentences emits prose one sentence per line, which is mdoc's own
// convention and the difference between a page mandoc lints clean and one it
// nags about on every entry.
func writeSentences(b *strings.Builder, text string) {
	text = sentenceEnd.ReplaceAllString(text, "$1$2\n")
	for _, sentence := range strings.Split(text, "\n") {
		if sentence = strings.TrimSpace(sentence); sentence == "" {
			continue
		}
		if !strings.HasSuffix(sentence, ".") && !strings.HasSuffix(sentence, "?") {
			sentence += "."
		}
		writeTextLine(b, sentence)
	}
}

// envVar matches the variables the usage's env line names, so the page keeps
// listing every variable the help does without a second list to maintain.
var envVar = regexp.MustCompile(`LANES_[A-Z_]+(=1)?`)

// envDocs carries the prose for variables the one-line help has no room to
// explain. A variable absent here still gets its entry, with whatever
// parenthetical the help gave it: only the wording is written down, never the
// list.
var envDocs = map[string]string{
	"LANES_ADDR":  "The daemon's address.",
	"LANES_DIR":   "The data directory, for the verbs that read the ledger file directly.",
	"LANES_TOKEN": "The lane token the agent-scoped verbs authenticate with.",
}

func writeEnvironment(b *strings.Builder, env string) {
	locs := envVar.FindAllStringIndex(env, -1)
	b.WriteString(".Bl -tag -width Ds\n")
	for i, loc := range locs {
		name, setTo, isSet := strings.Cut(env[loc[0]:loc[1]], "=")
		end := len(env)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		detail := strings.Trim(strings.TrimSpace(env[loc[1]:end]), ",")
		detail = strings.Trim(detail, "() ")
		if isSet && detail != "" {
			// "LANES_ADMIN=1 (bypass ...)": the value is half the instruction,
			// and the tag shows only the name.
			detail = "Set to " + setTo + " to " + detail
		} else {
			detail = upperFirst(detail)
		}
		b.WriteString(".It Ev " + name + "\n")
		if doc := envDocs[name]; doc != "" {
			writeTextLine(b, doc)
		}
		if detail != "" {
			writeSentences(b, detail)
		}
	}
	b.WriteString(".El\n")
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// roffText escapes what roff would otherwise interpret inside a text line.
func roffText(s string) string {
	return strings.ReplaceAll(s, `\`, `\e`)
}

// writeTextLine writes one line of page text: wrapped to the 80 bytes
// mandoc's lint asks of source lines, and with a leading dot or apostrophe
// disarmed, since either would otherwise turn the line into a request and
// swallow it whole.
func writeTextLine(b *strings.Builder, line string) {
	line = roffText(line)
	for line != "" {
		chunk := line
		if len(chunk) > 78 {
			cut := strings.LastIndex(chunk[:79], " ")
			if cut <= 0 {
				// One unbreakable token: let it run long rather than split a
				// word, and take the lint message over the broken word.
				cut = len(chunk)
				if i := strings.Index(chunk, " "); i > 0 {
					cut = i
				}
			}
			chunk = chunk[:cut]
		}
		line = strings.TrimSpace(line[len(chunk):])
		if strings.HasPrefix(chunk, ".") || strings.HasPrefix(chunk, "'") {
			chunk = `\&` + chunk
		}
		b.WriteString(chunk + "\n")
	}
}
