// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 Agenxy

package core

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"
)

// These JSON ops use the pre-change API, so this SAME test runs on 77b07ba.
// The new carrier has no envelope dependency: an old decoder ignores only the
// added field and executes the truthful ordinary activity checkpoint.
var contactCheckpointHistory = []string{
	`{"kind":"register","name":"lead","token":"lead-token","nonce":"lead-nonce","lane_kind":"persistent"}`,
	`{"kind":"register","name":"sender","token":"sender-token"}`,
	`{"kind":"register","name":"worker","token":"worker-token"}`,
	`{"kind":"grant_role","to":"lead","mode":"coordinator"}`,
	`{"kind":"send","agent_id":"sender","to":"worker","msg_type":"request","body":"unread"}`,
	`{"kind":"contact_escalated","msg_serial":5}`,
	`{"kind":"check_in","agent_id":"lead"}`,
	`{"kind":"activity_checkpoint","agent_id":"lead"}`,
	`{"kind":"resume","nonce":"lead-nonce","resume_id":"reactivate","token":"rotated-token"}`,
}

func foldContactCheckpointHistory(t *testing.T, added bool) map[string]any {
	t.Helper()
	st := NewState("contact-compat", DefaultLimits())
	for i, line := range contactCheckpointHistory {
		if added && i == 7 {
			line = `{"kind":"activity_checkpoint","agent_id":"lead","contact_notice_through_serial":6}`
		}
		var op Op
		if err := json.Unmarshal([]byte(line), &op); err != nil {
			t.Fatal(err)
		}
		before := st.Serial
		// Pin the ledger clock's location as well as its instant: time.Unix
		// otherwise uses the machine's Local zone when state is JSON-encoded.
		if _, _, err := st.Apply(&op, time.Unix(1700000000+int64(i), 0).UTC()); err != nil {
			t.Fatalf("fold op %d %s: %v", i, op.Kind, err)
		}
		if st.Serial != before+1 {
			t.Fatalf("fold op %d moved serial %d→%d", i, before, st.Serial)
		}
	}
	raw, err := json.Marshal(st)
	if err != nil {
		t.Fatal(err)
	}
	var view map[string]any
	if err := json.Unmarshal(raw, &view); err != nil {
		t.Fatal(err)
	}
	return view
}

func TestContactCheckpointLedgerCompatibility(t *testing.T) {
	before, added := foldContactCheckpointHistory(t, false), foldContactCheckpointHistory(t, true)
	// Captured from the unchanged 77b07ba fold, not regenerated by this test.
	raw, err := os.ReadFile("testdata/contact-checkpoint-historical.json")
	if err != nil {
		t.Fatal(err)
	}
	var historical map[string]any
	if err := json.Unmarshal(raw, &historical); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(before, historical) {
		t.Fatal("pre-change ledger no longer replays to the historical state")
	}
	for _, row := range added["Agents"].(map[string]any) {
		delete(row.(map[string]any), "contact_notice_read_serial")
	}
	if !reflect.DeepEqual(before, added) {
		t.Fatal("added carrier changed pre-existing replay state")
	}
	// Optional receipts let the old and new executables compare the complete
	// pre-change fold bytes, not a hand-selected subset of state.
	if dir := os.Getenv("DIBS_CONTACT_COMPAT_RECEIPT"); dir != "" {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			t.Fatal(err)
		}
		for name, view := range map[string]map[string]any{"historical.json": before, "added.json": added} {
			raw, err := json.MarshalIndent(view, "", "  ")
			if err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(dir, name), raw, 0o600); err != nil {
				t.Fatal(err)
			}
		}
	}
}
