package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"time"
)

// The daemon's manual.
//
// dibd is what an operator installs as a service, points at a listen address
// and configures with a file, and `man dibd` found nothing. The CLI has had a
// page since it had verbs; the process that actually holds the board did not,
// which is the wrong way round: the CLI is discoverable by typing `dibs help`,
// and a daemon under launchd is discoverable by reading about it.
//
// Generated rather than written, for the same reason the CLI's is: the flags
// are declared once in run(), and a hand-maintained page is a second copy that
// loses. The prose that cannot be derived (what the daemon IS, where its files
// live, what a restart costs) is here, because none of it is in a flag.
//
// Section 8, not 1. It is a system daemon, not a user command, and an operator
// looking for it will type `man 8 dibd` if they type a section at all.
func manCmd(args []string) error {
	fs := flag.NewFlagSet("man", flag.ContinueOnError)
	out := fs.String("out", "", "write the page to this file instead of stdout")
	date := fs.String("date", "", "page date, YYYY-MM-DD (default today). The release "+
		"passes the commit date so two builds of one commit produce one page")
	if err := fs.Parse(args); err != nil {
		return err
	}
	when := time.Now()
	if *date != "" {
		parsed, err := time.Parse("2006-01-02", *date)
		if err != nil {
			// Accept the RFC3339 the release pipeline has to hand, so the two
			// callers do not need to agree on a format.
			if parsed, err = time.Parse(time.RFC3339, *date); err != nil {
				return fmt.Errorf("date %q: want YYYY-MM-DD", *date)
			}
		}
		when = parsed
	}
	page := daemonManPage(when)
	if *out == "" {
		fmt.Print(page)
		return nil
	}
	return os.WriteFile(*out, []byte(page), 0o600)
}

func daemonManPage(when time.Time) string {
	var b strings.Builder
	// Raw, for macro lines that must land verbatim.
	w := func(s string) { b.WriteString(s + "\n") }
	// Prose, split one sentence per line and wrapped at 72 columns. mandoc
	// lints for both ("new sentence, new line" and an 80-byte input limit), and
	// a manual that does not lint clean is not a finished manual.
	p := func(s string) { b.WriteString(mdocProse(s)) }
	w(`.\" dibd.8: generated by ` + "`dibd -man`" + ` from the daemon's own flags.`)
	w(`.\" Regenerate rather than edit: a hand-maintained page is a second copy`)
	w(`.\" of the flags, and the copy loses.`)
	w(".Dd " + when.Format("January 2, 2006"))
	w(".Dt DIBD 8")
	w(".Os")
	w(".Sh NAME")
	w(".Nm dibd")
	w(".Nd coordination daemon for AI agents on one machine")
	w(".Sh SYNOPSIS")
	w(".Nm")
	w(".Op Fl dir Ar path")
	w(".Op Fl addr Ar host:port")
	w(".Op Fl allow-parallel")
	w(".Op Fl check")
	w(".Sh DESCRIPTION")
	w(".Nm")
	p("holds the board that agents coordinate through: who is registered, what each")
	p("is working on, the mail between them, and advisory claims on directories.")
	p("Agents reach it over MCP; people reach it with")
	w(".Xr dibs 1 .")
	w(".Pp")
	p("State is an append-only, hash-chained, encrypted log. The board is the fold of")
	p("that log, so a restart rebuilds it rather than losing it: stopping and starting")
	w(".Nm")
	p("costs the replay, which is milliseconds on an ordinary board, and no agent has")
	p("to re-register. Use")
	w(".Cm dibs upgrade")
	p("to move a running fleet onto a new build; it proves the new binary can rebuild")
	p("the board before it stops anything.")
	w(".Pp")
	p("One daemon owns one data directory, enforced with a lock. A second")
	w(".Nm")
	p("on the same machine is refused unless")
	w(".Fl allow-parallel")
	p("is given, because two boards split a fleet in a way that looks like everything")
	p("working.")
	w(".Sh OPTIONS")
	w(".Bl -tag -width Ds")
	for _, f := range daemonFlags() {
		w(".It Fl " + f.name + (map[bool]string{true: "", false: " Ar value"})[f.boolean])
		p(f.usage)
		if f.def != "" {
			p("The default is")
			w(".Ar " + f.def + " .")
		}
	}
	w(".El")
	w(".Sh ENVIRONMENT")
	w(".Bl -tag -width Ds")
	w(".It Ev DIBS_DIR")
	p("Data directory. Overrides the default and is overridden by")
	w(".Fl dir .")
	w(".It Ev DIBS_ADDR")
	p("Listen address. Sits between")
	w(".Fl addr")
	p("and the configuration file.")
	w(".El")
	w(".Sh FILES")
	w(".Bl -tag -width Ds")
	w(".It Pa ~/.dibs/dibs.toml")
	p("Configuration. Every setting is documented in docs/CONFIGURATION.md; an")
	p("unknown key stops the daemon rather than being ignored.")
	w(".It Pa ~/.dibs/ledger.jsonl")
	p("The board itself: append-only, hash-chained, encrypted at rest.")
	w(".It Pa ~/.dibs/local.secret")
	p("The coordination secret every agent on this machine authenticates with.")
	w(".It Pa ~/.dibs/key")
	p("The key the ledger and blob store are encrypted with. Losing it loses the")
	p("board's contents; the hash chain remains verifiable.")
	w(".It Pa ~/.dibs/coordinator.claim")
	p("Present only while the board has no coordinator. The first successful")
	w(".Cm claim_coordinator")
	p("consumes it.")
	w(".El")
	w(".Sh EXIT STATUS")
	w(".Ex -std")
	p("A ledger that will not replay is a refusal to start, not a warning: the board")
	p("is the log, so a record that will not apply means every later record describes")
	p("a board that can no longer be reconstructed. See")
	w(".Cm dibs admin repair-ledger .")
	w(".Sh SEE ALSO")
	w(".Xr dibs 1")
	w(".Pp")
	p("PHILOSOPHY.md for what Dibs is and is not, SPEC.md for the protocol,")
	p("SECURITY.md for the trust boundaries, docs/CONFIGURATION.md for every setting.")
	return b.String()
}

// daemonFlag is one documented flag, described where it is declared.
type daemonFlag struct {
	name    string
	usage   string
	def     string
	boolean bool
}

// daemonFlags walks the real flag set, so a flag added to run() appears in the
// manual without anybody remembering to add it. TestTheDaemonManualCoversEvery
// Flag fails if this drifts.
func daemonFlags() []daemonFlag {
	var out []daemonFlag
	fs := flag.NewFlagSet("dibd", flag.ContinueOnError)
	registerDaemonFlags(fs)
	fs.VisitAll(func(f *flag.Flag) {
		out = append(out, daemonFlag{
			name:    f.Name,
			usage:   strings.Join(strings.Fields(f.Usage), " "),
			def:     f.DefValue,
			boolean: f.DefValue == "false" || f.DefValue == "true",
		})
	})
	return out
}

// mdocProse renders a paragraph the way mandoc wants it: one sentence per
// line, wrapped short. Both are lint rules, and both exist because roff joins
// input lines and a sentence boundary at end-of-line is how it knows to put two
// spaces after the full stop.
func mdocProse(text string) string {
	var out strings.Builder
	for _, sentence := range splitSentences(text) {
		out.WriteString(wrapAt(sentence, 72))
	}
	return out.String()
}

// splitSentences breaks on ". " where the next word starts a sentence. Naive on
// purpose: an abbreviation split across two lines renders identically, and the
// alternative is a sentence tokeniser in a manual generator.
func splitSentences(text string) []string {
	var out []string
	rest := strings.Join(strings.Fields(text), " ")
	for {
		i := strings.Index(rest, ". ")
		if i < 0 {
			if rest != "" {
				out = append(out, rest)
			}
			return out
		}
		out = append(out, rest[:i+1])
		rest = strings.TrimSpace(rest[i+2:])
	}
}

// wrapAt folds a sentence, never mid-word.
func wrapAt(s string, width int) string {
	var out strings.Builder
	line := ""
	for _, word := range strings.Fields(s) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= width:
			line += " " + word
		default:
			out.WriteString(line + "\n")
			line = word
		}
	}
	if line != "" {
		out.WriteString(line + "\n")
	}
	return out.String()
}
